# SPDX-FileCopyrightText: 2024 Fraunhofer FKIE
# SPDX-FileContributor: Marten Ringwelski <git@maringuu.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# The port that should expose the FACT frontend
PORT = 5000
# The number of CPUs to assign to the virtual machine
CPUS = 8
# The amount of RAM in megabytes
RAM = 8 * 1024
# The disksize to use. If you intend to upload the whole corpus,
# you need about 5,000GB.
DISK = "100GB"

Vagrant.configure("2") do |config|
  config.vagrant.plugins = "vagrant-disksize"

  config.vm.box = "fact-cad/FACT-master"
  config.vm.box_version = "20231223"

  config.vm.network "forwarded_port", guest: 5000, host: PORT

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.disksize.size = DISK
  #config.vm.disk :disk, size: DISK, primary: true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = CPUS
    vb.memory = RAM
  end
end

