#!/bin/bash

rm -rf .venv
python3 -m venv .venv
source "./.venv/bin/activate"

pip install scrapy
pip install .

sudo add-apt-repository ppa:mozillateam/ppa -y
echo '
Package: *
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1001
' | sudo tee /etc/apt/preferences.d/mozilla-firefox

sudo apt update && sudo apt install firefox -y
